Variables:

  ClientSide:

    Prefix: "!"
    Status: 2
    Token: "ODE5OTg1MDc5MzE2NjQzODkz.YEuknQ.PaImie90ORtc7NrnGo08EgNnUCk"

    Webhooks:
      System: "https://discordapp.com/api/webhooks/815708355371860069/gy3_edx9paMdTg6f-0WL2qOlWnGKalV_10SPwK3jjdWV3f4dPSbvLStyDmClkAVQBRgu"

    GitHub:
      ShimariData: "https://raw.githubusercontent.com/Drageast/shimari-data/master/shimari.yaml"
      Balancing: "https://raw.githubusercontent.com/Drageast/shimari-data/master/balancing.yaml"

    Channels:
      Shimari: "shimari"
      Shimari_TEST: 837727003209760819

    MongoDB:
      URL: "mongodb+srv://Drageast:Schmidt04@cluster0.r1bgi.mongodb.net/Adenn?retryWrites=true&w=majority"
      Base: "Adenn"
      Connection1: "Ticket"
      Connection2: "Uccounts"

  Developer: [431017472083099660, 440136099235364864]

  API:
    NASA: "zvpl6l45Kx7tFk1houKoBdtiIba6wexuphZFjZ0N"
    Google: "AIzaSyC_H3iPD44OQneMTTJigL9WEpHfH-7TblU"
    Google_ID: "869d2dcdf80a96e4f"

Bilder:

  Clock: "https://i.imgur.com/pJ2l5Gl.jpg"
  NASA: "https://i.imgur.com/80f8CeM.jpg"
  Credits: "https://i.imgur.com/2ikqdp6.jpg"

Embed:

  HTitle: "Die Faehigkeit zu sprechen, macht dich noch nicht intelligent."