Variables:

  ClientSide:

    Prefix: ""
    Status: 1
    Token: ""

    Webhooks:
      System: ""

    GitHub:
      ShimariData: ""
      Balancing: ""

    Channels:
      Shimari: ""
      Shimari_TEST: ""

    MongoDB:
      URL: ""
      Base: ""
      Connection1: ""
      Connection2: ""

  Developer: []

  API:
    NASA: ""
    Google: ""
    Google_ID: ""

Bilder:

  Clock: "https://i.imgur.com/pJ2l5Gl.jpg"
  NASA: "https://i.imgur.com/80f8CeM.jpg"
  Credits: "https://i.imgur.com/2ikqdp6.jpg"
  Database: "https://i.imgur.com/dhVs9gQ.png"

Embed:

  HTitle: "Die Faehigkeit zu sprechen, macht dich noch nicht intelligent."
